google_api_key = "AIzaSyBxRClPYVk9h8B5PLDaNAkQkoOTQ9EDebA"
openai_api_key = "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"
